version: '3.5'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    ports:
      - 5672:5672

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ~/datadir/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  orders_api:
    container_name: orders_api
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
    command: bash -c "sleep 2 && npm run dev:orders"
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3001:3001
      - 9230:9229
    depends_on:
      - rabbitmq
      - mysql
    links:
      - rabbitmq
      - mysql

  payments_api:
    container_name: payments_api
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
    command: bash -c "sleep 2 && npm run dev:payments"
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3002:3002
      - 9231:9229
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
